name: Simple GitHub Pages Deploy

on:
  push:
    branches: [ main, master ]

jobs:
  deploy:
    permissions:
      contents: read
      pages: write
      id-token: write
    environment:
      name: github-pages
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Replace secrets in env.js
        run: |
          sed -i 's/{{GITHUB_ADMIN_USERNAME}}/admin/g' env.js
          sed -i 's/{{GITHUB_ADMIN_PASSWORD}}/gallery2024/g' env.js

      - uses: actions/configure-pages@v4
      - uses: actions/upload-pages-artifact@v3
        with:
          path: '.'
      - uses: actions/deploy-pages@v4